[keyboard]
bindings = [
  { key = "F11",                             action = "ToggleFullscreen" },
]


[general]
import = [
    "~/.config/alacritty/themes/themes/iterm.toml"
]



[window]
startup_mode = "Maximized"


[cursor.style]
blinking              = "Always"
